function [netObj] = model_lstm_decoder(netObj, time)
% model_lstm_decoder define the model of LSTM of the decoder part with
% Backpropogation Through Time (BPTT).

label = sprintf('_t%d', time);
if time == 1
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_inputgate_codex' label]...
        'bottom' 'codex' ...
        'top'    ['decoder_inputgate_codex' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_inputgate_codex_w', 'decoder_inputgate_codex_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.sigmoid'...
        'name'   ['decoder_inputgate_sigmoid' label]...
        'bottom' ['decoder_inputgate_codex' label]...
        'top'    ['decoder_inputgate_sigmoid' label]...
        });
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_forgetgate_codex' label]...
        'bottom' 'codex' ...
        'top'    ['decoder_forgetgate_codex' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_forgetgate_codex_w', 'decoder_forgetgate_codex_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.sigmoid'...
        'name'   ['decoder_forgetgate_sigmoid' label]...
        'bottom' ['decoder_forgetgate_codex' label]...
        'top'    ['decoder_forgetgate_sigmoid' label]...
        });
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_modulategate_codex' label]...
        'bottom' 'codex' ...
        'top'    ['decoder_modulategate_codex' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_modulategate_codex_w', 'decoder_modulategate_codex_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.hybtangent'...
        'name'   ['decoder_modulategate_tanh' label]...
        'bottom' ['decoder_modulategate_codex' label]...
        'top'    ['decoder_modulategate_tanh' label]...
        });
    netObj.newLayer({
        'type'   'layers.eltwise' ...
        'name'   ['decoder_cell' label] ...
        'bottom' {['decoder_modulategate_tanh' label], ['decoder_inputgate_sigmoid' label]} ...
        'top'    ['decoder_cell' label]...
        'operation' 'prod'
        })
    netObj.newLayer({
        'type' 'layers.hybtangent'...
        'name'   ['decoder_cell_tanh' label]...
        'bottom' ['decoder_cell' label] ...
        'top'    ['decoder_cell_tanh' label]
        })
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_outputgate_codex' label]...
        'bottom' 'codex' ...
        'top'    ['decoder_outputgate_codex' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_outputgate_codex_w', 'decoder_outputgate_codex_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_outputgate_cell' label]...
        'bottom' ['decoder_cell' label] ...
        'top'    ['decoder_outputgate_cell' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_outputgate_cell_w', 'decoder_outputgate_cell_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.eltwise'...
        'name'   ['decoder_outputgate' label] ...
        'bottom' {['decoder_outputgate_codex' label], ['decoder_outputgate_cell' label]}...
        'top'    ['decoder_outputgate' label]...
        'operation' 'sum'
        })
    netObj.newLayer({
        'type'   'layers.sigmoid'...
        'name'   ['decoder_outputgate_sigmoid' label]...
        'bottom' ['decoder_outputgate' label]...
        'top'    ['decoder_outputgate_sigmoid' label]...
        });
    netObj.newLayer({
        'type'   'layers.eltwise'...
        'name'   ['decoder_final' label] ...
        'bottom' {['decoder_outputgate_sigmoid' label], ['decoder_cell_tanh' label]}...
        'top'    ['decoder_final' label]...
        'operation' 'prod'
        })
else
    label_last = sprintf('_t%d', time-1);
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_inputgate_codex' label]...
        'bottom' 'codex' ...
        'top'    ['decoder_inputgate_codex' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_inputgate_codex_w', 'decoder_inputgate_codex_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_inputgate_final' label]...
        'bottom' ['decoder_final' label_last] ...
        'top'    ['decoder_inputgate_final' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_inputgate_final_w', 'decoder_inputgate_final_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_inputgate_cell' label]...
        'bottom' ['decoder_cell' label_last] ...
        'top'    ['decoder_inputgate_cell' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_inputgate_cell_w', 'decoder_inputgate_cell_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.eltwise'...
        'name'   ['decoder_inputgate_cell_final' label] ...
        'bottom' {['decoder_inputgate_cell' label], ['decoder_inputgate_final' label]}...
        'top'    ['decoder_inputgate_cell_final' label]...
        'operation' 'sum'
        })
    netObj.newLayer({
        'type'   'layers.eltwise'...
        'name'   ['decoder_inputgate' label] ...
        'bottom' {['decoder_inputgate_codex' label], ['decoder_inputgate_cell_final' label]} ...
        'top'    ['decoder_inputgate' label]...
        'operation' 'sum'
        })
    netObj.newLayer({
        'type'   'layers.sigmoid'...
        'name'   ['decoder_inputgate_sigmoid' label]...
        'bottom' ['decoder_inputgate' label]...
        'top'    ['decoder_inputgate_sigmoid' label]...
        });
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_forgetgate_codex' label]...
        'bottom' 'codex' ...
        'top'    ['decoder_forgetgate_codex' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_forgetgate_codex_w', 'decoder_forgetgate_codex_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_forgetgate_cell' label]...
        'bottom' ['decoder_cell' label_last] ...
        'top'    ['decoder_forgetgate_cell' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_forgetgate_cell_w', 'decoder_forgetgate_cell_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_forgetgate_final' label]...
        'bottom' ['decoder_final' label_last] ...
        'top'    ['decoder_forgetgate_final' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_forgetgate_final_w', 'decoder_forgetgate_final_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.eltwise'...
        'name'   ['decoder_forgetgate_cell_final' label] ...
        'bottom' {['decoder_forgetgate_cell' label], ['decoder_forgetgate_final' label]}...
        'top'    ['decoder_forgetgate_cell_final' label]...
        'operation' 'sum'
        })
    netObj.newLayer({
        'type'   'layers.eltwise' ...
        'name'   ['decoder_forgetgate' label]...
        'bottom' {['decoder_forgetgate_codex' label], ['decoder_forgetgate_cell_final' label]} ...
        'top'    ['decoder_forgetgate' label]...
        'operation' 'sum'
        })
    netObj.newLayer({
        'type'   'layers.sigmoid'...
        'name'   ['decoder_forgetgate_sigmoid' label]...
        'bottom' ['decoder_forgetgate' label] ...
        'top'    ['decoder_forgetgate_sigmoid' label]...
        });
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_modulategate_codex' label]...
        'bottom' 'codex' ...
        'top'    ['decoder_modulategate_codex' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_modulategate_codex_w', 'decoder_modulategate_codex_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_modulategate_final' label]...
        'bottom' ['decoder_final' label_last] ...
        'top'    ['decoder_modulategate_final' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_modulategate_final_w', 'decoder_modulategate_final_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });

    netObj.newLayer({
        'type'   'layers.eltwise'...
        'name'   ['decoder_modulategate' label] ...
        'bottom' {['decoder_modulategate_codex' label], ['decoder_modulategate_final' label]}...
        'top'    ['decoder_modulategate' label]...
        'operation' 'sum'
        })
    netObj.newLayer({
        'type'   'layers.hybtangent'...
        'name'   ['decoder_modulategate_tanh' label]...
        'bottom' ['decoder_modulategate' label]...
        'top'    ['decoder_modulategate_tanh' label]...
        });
    netObj.newLayer({
        'type'   'layers.eltwise' ...
        'name'   ['decoder_cell_mod_input' label] ...
        'bottom' {['decoder_modulategate_tanh' label], ['decoder_inputgate_sigmoid' label]} ...
        'top'    ['decoder_cell_mod_input' label]...
        'operation' 'prod'
        })
    netObj.newLayer({
        'type'   'layers.eltwise' ...
        'name'   ['decoder_cell_cell_forget' label] ...
        'bottom' {['decoder_cell' label_last], ['decoder_forgetgate_sigmoid' label]} ...
        'top'    ['decoder_cell_cell_forget' label]...
        'operation' 'prod'
        })
    netObj.newLayer({
        'type'   'layers.eltwise' ...
        'name'   ['decoder_cell' label] ...
        'bottom' {['decoder_cell_cell_forget' label], ['decoder_cell_mod_input' label]} ...
        'top'    ['decoder_cell' label]...
        'operation' 'sum'
        })
    netObj.newLayer({
        'type'   'layers.hybtangent'...
        'name'   ['decoder_cell_tanh' label]...
        'bottom' ['decoder_cell' label] ...
        'top'    ['decoder_cell_tanh' label]
        })
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_outputgate_codex' label]...
        'bottom' 'codex' ...
        'top'    ['decoder_outputgate_codex' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_outputgate_codex_w', 'decoder_outputgate_codex_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_outputgate_cell' label]...
        'bottom' ['decoder_cell' label] ...
        'top'    ['decoder_outputgate_cell' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_outputgate_cell_w', 'decoder_outputgate_cell_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.convolution'...
        'name'   ['decoder_outputgate_final' label]...
        'bottom' ['decoder_final' label_last] ...
        'top'    ['decoder_outputgate_final' label]...
        'convolution_param' {
            'num_output'  128 ...
            'kernel_size' 1  ...
            'pad'         0  ...
            'stride'      1  ...
            }...
        'weight_param' {
            'name'         {'decoder_outputgate_final_w', 'decoder_outputgate_final_b'} ...
            'generator'    {@nn.generator.xavier, @nn.generator.constant} ...
            'learningRate' [1 2]
            }
        });
    netObj.newLayer({
        'type'   'layers.eltwise'...
        'name'   ['decoder_outputgate_cell_final' label] ...
        'bottom' {['decoder_outputgate_cell' label], ['decoder_outputgate_final' label]}...
        'top'    ['decoder_outputgate_cell_final' label]...
        'operation' 'sum'
        })
    netObj.newLayer({
        'type'   'layers.eltwise'...
        'name'   ['decoder_outputgate' label] ...
        'bottom' {['decoder_outputgate_codex' label], ['decoder_outputgate_cell_final' label]}...
        'top'    ['decoder_outputgate' label]...
        'operation' 'sum'
        })
    netObj.newLayer({
        'type'   'layers.sigmoid'...
        'name'   ['decoder_outputgate_sigmoid' label]...
        'bottom' ['decoder_outputgate' label]...
        'top'    ['decoder_outputgate_sigmoid' label]...
        });
    netObj.newLayer({
        'type'   'layers.eltwise'...
        'name'   ['decoder_final' label] ...
        'bottom' {['decoder_outputgate_sigmoid' label], ['decoder_cell_tanh' label]}...
        'top'    ['decoder_final' label]...
        'operation' 'prod'
        })
end